[package]
name = "test-rust-env"
version = "0.1.0"
authors = ["youxuan <1454739828@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
